function Twenty_Seven_Node_Brick_Inverse = Twenty_Seven_Node_Brick_Inverse()

	Twenty_Seven_Brick_Coordinates = Build_Brick_Coordinates();
	Twenty_Seven_Brick_Coordinates = Twenty_Seven_Brick_Coordinates(1:27,:);

	Twenty_Seven_Node_Brick_Inverse = zeros(27,27);

	SQRT_3_5 = sqrt(3/5);

	for j=1:27
		for i=1:8
			Twenty_Seven_Node_Brick_Inverse(j,i) = 1/8*(1+Twenty_Seven_Brick_Coordinates(j,1)*Twenty_Seven_Brick_Coordinates(i,1)*SQRT_3_5)* ...
												(1+Twenty_Seven_Brick_Coordinates(j,2)*Twenty_Seven_Brick_Coordinates(i,2)*SQRT_3_5)* ...
												(1+Twenty_Seven_Brick_Coordinates(j,3)*Twenty_Seven_Brick_Coordinates(i,3)*SQRT_3_5)* ...
												((Twenty_Seven_Brick_Coordinates(j,1)*Twenty_Seven_Brick_Coordinates(i,1)*SQRT_3_5)* ...
												 (Twenty_Seven_Brick_Coordinates(j,2)*Twenty_Seven_Brick_Coordinates(i,2)*SQRT_3_5)* ...
												 (Twenty_Seven_Brick_Coordinates(j,3)*Twenty_Seven_Brick_Coordinates(i,3)*SQRT_3_5));
		end
		for i=[9,11,13,15]
			Twenty_Seven_Node_Brick_Inverse(j,i) = 1/4*(1-(Twenty_Seven_Brick_Coordinates(j,1)*SQRT_3_5)^2)* ...
												(1+Twenty_Seven_Brick_Coordinates(j,2)*Twenty_Seven_Brick_Coordinates(i,2)*SQRT_3_5)* ...
												(1+Twenty_Seven_Brick_Coordinates(j,3)*Twenty_Seven_Brick_Coordinates(i,3)*SQRT_3_5)* ...
												((Twenty_Seven_Brick_Coordinates(j,2)*Twenty_Seven_Brick_Coordinates(i,2)*SQRT_3_5)* ...
												 (Twenty_Seven_Brick_Coordinates(j,3)*Twenty_Seven_Brick_Coordinates(i,3)*SQRT_3_5));
		end
		for i=[10,12,14,16]
			Twenty_Seven_Node_Brick_Inverse(j,i) = 1/4*(1-(Twenty_Seven_Brick_Coordinates(j,2)*SQRT_3_5)^2)* ...
												(1+Twenty_Seven_Brick_Coordinates(j,1)*Twenty_Seven_Brick_Coordinates(i,1)*SQRT_3_5)* ...
												(1+Twenty_Seven_Brick_Coordinates(j,3)*Twenty_Seven_Brick_Coordinates(i,3)*SQRT_3_5)* ...
												((Twenty_Seven_Brick_Coordinates(j,1)*Twenty_Seven_Brick_Coordinates(i,1)*SQRT_3_5)* ...
												 (Twenty_Seven_Brick_Coordinates(j,3)*Twenty_Seven_Brick_Coordinates(i,3)*SQRT_3_5));
		end
		for i=[17,18,19,20]
			Twenty_Seven_Node_Brick_Inverse(j,i) = 1/4*(1-(Twenty_Seven_Brick_Coordinates(j,3)*SQRT_3_5)^2)* ...
												(1+Twenty_Seven_Brick_Coordinates(j,1)*Twenty_Seven_Brick_Coordinates(i,1)*SQRT_3_5)* ...
												(1+Twenty_Seven_Brick_Coordinates(j,2)*Twenty_Seven_Brick_Coordinates(i,2)*SQRT_3_5)* ...
												((Twenty_Seven_Brick_Coordinates(j,1)*Twenty_Seven_Brick_Coordinates(i,1)*SQRT_3_5)* ...
												 (Twenty_Seven_Brick_Coordinates(j,2)*Twenty_Seven_Brick_Coordinates(i,2)*SQRT_3_5));
		end
		for i=[21]
			Twenty_Seven_Node_Brick_Inverse(j,i) = 1/4*(1-(Twenty_Seven_Brick_Coordinates(j,1)*SQRT_3_5)^2)* ...
													   (1-(Twenty_Seven_Brick_Coordinates(j,2)*SQRT_3_5)^2)* ...
													   (1-(Twenty_Seven_Brick_Coordinates(j,3)*SQRT_3_5)^2);
		end
		for i=[22,24]
			Twenty_Seven_Node_Brick_Inverse(j,i) = 1/2*(1-(Twenty_Seven_Brick_Coordinates(j,1)*SQRT_3_5)^2)* ...
													   (1-(Twenty_Seven_Brick_Coordinates(j,3)*SQRT_3_5)^2)* ...
													   (1+Twenty_Seven_Brick_Coordinates(j,2)*Twenty_Seven_Brick_Coordinates(i,2)*SQRT_3_5)* ...
													   (Twenty_Seven_Brick_Coordinates(j,2)*Twenty_Seven_Brick_Coordinates(i,2)*SQRT_3_5);
		end
		for i=[23,25]
			Twenty_Seven_Node_Brick_Inverse(j,i) = 1/2*(1-(Twenty_Seven_Brick_Coordinates(j,2)*SQRT_3_5)^2)* ...
													   (1-(Twenty_Seven_Brick_Coordinates(j,3)*SQRT_3_5)^2)* ...
													   (1+Twenty_Seven_Brick_Coordinates(j,1)*Twenty_Seven_Brick_Coordinates(i,1)*SQRT_3_5)* ...
													   (Twenty_Seven_Brick_Coordinates(j,1)*Twenty_Seven_Brick_Coordinates(i,1)*SQRT_3_5);
		end
		for i=[26,27]
			Twenty_Seven_Node_Brick_Inverse(j,i) = 1/2*(1-(Twenty_Seven_Brick_Coordinates(j,1)*SQRT_3_5)^2)* ...
													   (1-(Twenty_Seven_Brick_Coordinates(j,2)*SQRT_3_5)^2)* ...
													   (1+Twenty_Seven_Brick_Coordinates(j,3)*Twenty_Seven_Brick_Coordinates(i,3)*SQRT_3_5)* ...
													   (Twenty_Seven_Brick_Coordinates(j,3)*Twenty_Seven_Brick_Coordinates(i,3)*SQRT_3_5);
		end
	end

	Twenty_Seven_Node_Brick_Inverse

	Twenty_Seven_Node_Brick_Inverse = inv(Twenty_Seven_Node_Brick_Inverse);

end